version: '3.8'

services:
  postgres:
    container_name: ${APP_NAME}-db
    image: postgres
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB_NAME}
    volumes:
       - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
    postgres: